import React from 'react'
import { useNavigate } from 'react-router-dom'
import { preview } from '../assets'
import { getRandomPrompt } from '../utils'
import { FromField } from '../Components'
const CreatePost = () => {
  const navigate = useNavigate();
  useState[form, setForm] = useState({
    name: '',
    prompt: '',
    photo: '',
  });
  const [generatingImg, setGeneratingImg] = useState(false);
  const [loading, setLoading] = useState(false);
  const handleSubmit = () => {

  }
  const handleChange = (e) => {

  }
  const handleSurpriseMe = () => {

  }
  return (
    <section className='max-w-7xl mx-auto'>
      <div>
         
            <h1 className='font-extrabold text-[#222328] text-[32px]'>
                Create
            </h1>
            <p className='mt-2 text-[#666e75] text-[16px] max-w [500px] '>Create throungh a collection of images and visually stuning generated by VisageForge</p>
       
      </div>
      <form className='mt-16 max-w-3xl' on submit={handleSubmit}>
        <div className='flex flex-col gap-5'>
          <FromField
            labelName="Your Name"
            type="text"
            name="name"
            placeholder="Ex., John Doe"
            value={form.name}
            handleChange={handleChange}
          />
          <FromField
            labelName="Prompt"
            type="text"
            name="Prompt"
            placeholder="Two futuristic towers with a skybridge covered in lush foliage, digital art"
            value={form.prompt}
            handleChange={handleChange}
            isSurpriseMe
            handleSurpriseMe={handleSurpriseMe}
          />
          
            
         
          
        </div>

      </form>
    </section>
  )
}

export default CreatePost